name: Secret Test Run

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Secret Loading
        run: |
          APPS_SCRIPT_URL="${{ secrets.APPS_SCRIPT_URL }}"

          # This will show you exactly what the shell sees for the URL variable
          echo "URL LENGTH: ${#APPS_SCRIPT_URL}"

          # If the length is correct (check your URL length manually) and this runs, 
          # the secret loading is fine.
